version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Asia/Tokyo"
      time: "04:00"
    commit-message:
      prefix: "chore"
    target-branch: "main"
